#!/bin/bash
set -x #echo on

## Important
# sudo mv /etc/hosts /etc/hosts.ori
# cat << EOF | sudo tee /etc/hosts
# EOF

kayobe control host bootstrap

kayobe overcloud host configure

cd ~/kayobe/src/kayobe-config
git add etc/kayobe/kolla/passwords.yml
git commit -m "Add autogenerated passwords for Kolla Ansible"

kayobe overcloud container image pull
sudo docker images

kayobe overcloud service deploy
